name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (Frontend)
        run: |
          cd frontend
          npm install
          npm run build
      
      - name: Install and Build Admin Frontend
        run: |
          cd admin-frontend
          npm install
          npm run build
      
      - name: Install dependencies (Backend)
        run: |
          cd backend
          npm install

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "."
          target: "/home/ubuntu/recipe-app"

      - name: Restart Backend and NGINX
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/recipe-app/backend
            pm2 stop all || true
            pm2 start app.js --name recipe-backend
            
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/recipe-app/frontend/dist/* /var/www/html/
            
            sudo rm -rf /var/www/admin/*
            sudo mkdir -p /var/www/admin
            sudo cp -r /home/ubuntu/recipe-app/admin-frontend/dist/* /var/www/admin/
            
            sudo systemctl restart nginx
