name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        source: "."
        target: "/home/ubuntu/recipe-app"
        
    - name: Build & Restart Services on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/recipe-app

          # Setup Backend
          cd backend
          npm install
          pm2 restart recipe-backend || pm2 start app.js --name recipe-backend
           
          # Setup Frontend
          cd ../frontend
          npm install
          npm run build

          # Deploy Frontend to Nginx Web Root
          sudo rm -rf /var/www/html/*
          sudo cp -r dist/* /var/www/html/
          sudo systemctl restart nginx
   